name = "blog-app"
compatibility_date = "2024-02-23"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTMyOGU0NDMtYTc4My00YWZiLWE4ZjgtNTc2OWY3NmEyNWJkIiwidGVuYW50X2lkIjoiYTNkOWY2NGI3M2Y3NzM2ZDFlMjA0NmE1YzAyNjAyODY4OTZjOWUwNDFjNzAxYmU2Y2Q3MzRjMDc5ODA1ZjQxYyIsImludGVybmFsX3NlY3JldCI6Ijk4ZjMyMGVmLWFjMTEtNDIwNi1iOGRkLTEwM2ViYzRmNDg2NSJ9.m3g0_4UWP1ugYyH39YCqM2ivd8PJLENwF2vybFnllA4"